version: "1.1"
services:
  mynode:
    image: prom/node-exporter:latest
    container_name: "promonitor"
    hostname: "mynode"
    ports:
      - "8081:8081"
    volumes:
      - "./scripts:/opt"
      - "./logs:/var/log/monitor"
    restart: always
    healthcheck:
      test: "wget --spider http://mynode:8081/health"
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      mydb:
        condition: service_healthy
    entrypoint: sh /opt/start_node_exporter.sh
  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    restart: always
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: always
    ports:
      - 3000:3000
  mydb:
    image: mariadb:latest
    container_name: mydb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
      - "./sql:/opt"
    environment:
      - "MYSQL_ROOT_PASSWORD=mariadb"
      - "MYSQL_DATABASE=monitor"
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin -uroot -pmariadb ping --silent" ]
      interval: 10s
      timeout: 10s
      retries: 5
